// ── Demo fallback data used before a real scrape has run ───────────────────
import type { ReelType } from './transform'

export const creatorScore = {
  score: 78,
  total: 100,
  grade: 'B+',
  subtitle: 'Based on your last 10 reels · last 45 days',
  metrics: [
    { label: 'Engagement Rate',      value: '12.8%',   pct: 95, color: 'green',  badge: 'Strong'  },
    { label: 'Posting Consistency',  value: '1.5×/wk', pct: 52, color: 'amber',  badge: 'Average' },
    { label: 'Content Variety',      value: '1 format', pct: 15, color: 'red',    badge: 'Weak'    },
    { label: 'Hook Quality',         value: '86/100',  pct: 86, color: 'indigo', badge: 'Strong'  },
    { label: 'Hashtag Strategy',     value: '58/100',  pct: 58, color: 'amber',  badge: 'Average' },
  ],
}

export const quickStats = [
  {
    icon: '📹',
    iconBg: 'rgba(99,102,241,.12)',
    value: 10,
    suffix: '',
    label: 'Total Reels',
    trend: '↑ 9 reels this month',
    trendType: 'up' as const,
  },
  {
    icon: '👁️',
    iconBg: 'rgba(16,185,129,.12)',
    value: 217.5,
    suffix: 'K',
    label: 'Avg Views / Reel',
    trend: '↑ 1 reel hit 1.5M views',
    trendType: 'up' as const,
  },
  {
    icon: '⏰',
    iconBg: 'rgba(245,158,11,.12)',
    value: null,
    staticText: 'Sat 3PM',
    suffix: '',
    label: 'Your Best Posting Time',
    trend: '1.5M views on Sat Apr 26',
    trendType: 'up' as const,
  },
  {
    icon: '💬',
    iconBg: 'rgba(6,182,212,.12)',
    value: 12.8,
    suffix: '%',
    label: 'Engagement Rate',
    trend: '↑ 4× above avg (3.2%)',
    trendType: 'up' as const,
  },
]

export const competitors = [
  {
    initials: 'NH',
    gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
    handle: '@nateherkai',
    followers: '—',
    followersRaw: 0,
    engRate: '—',
    topViews: '—',
    topViewsRaw: 0,
  },
  {
    initials: 'NI',
    gradient: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
    handle: '@nicksarev',
    followers: '—',
    followersRaw: 0,
    engRate: '—',
    topViews: '—',
    topViewsRaw: 0,
  },
]

export const nextReelIdea = {
  viralScore: 91,
  hook: '"I turned one Claude Code prompt into a full business system — here\'s the exact setup"',
  why: '🎯 Your top 2 performing reels both used a personal achievement + specific number hook ("144 employees", "50K followers in 17 days"). Your audience is 4.2× more likely to comment when you combine story + social proof + a free offer. This format is your proven viral pattern.',
  tags: [
    { type: 'audio',  dot: '#8b5cf6', label: 'Trending: lo-fi beats (calm focus)' },
    { type: 'time',   dot: '#10b981', label: 'Post Sat 3PM' },
    { type: 'format', dot: '#06b6d4', label: 'Talking Head + Text Overlay' },
    { type: 'trend',  dot: '#f59e0b', label: '🔥 Claude Code is trending' },
  ],
}

export const trendingAudio = [
  {
    name: 'Aesthetic — Xilo',
    sub: '2.3M reels · ↑ 340% this week',
    badge: '🔥 Hot',
    badgeColor: '#8b5cf6',
    delays: [0, 0.1, 0.2, 0.15, 0.05, 0.25, 0.1],
  },
  {
    name: 'STAY — Justin Bieber',
    sub: '1.8M reels · ↑ 120% this week',
    badge: '📈 Rising',
    badgeColor: '#f59e0b',
    delays: [0.1, 0.2, 0.05, 0.15, 0.3, 0.0, 0.25],
  },
  {
    name: 'Calm Down — Rema',
    sub: '4.1M reels · Evergreen',
    badge: '♾️ Stable',
    badgeColor: '#06b6d4',
    delays: [0.2, 0.0, 0.15, 0.3, 0.05, 0.1, 0.25],
  },
  {
    name: 'original sound — mxmtoon',
    sub: '567K reels · ↑ 890% this week',
    badge: '🚀 Breakout',
    badgeColor: '#8b5cf6',
    delays: [0.05, 0.25, 0.1, 0.0, 0.2, 0.15, 0.3],
  },
]

// ── Demo recent reels ───────────────────────────────────────────────────────
export const recentReels = [
  {
    id: '3893371845881910643',
    emoji: '🎓',
    thumbGradient: 'linear-gradient(135deg,#1e1b4b,#312e81)',
    title: '"Everyone is talking about the same basic Claude tips — here are 3 features nobody shows you"',
    type: 'Educational' as ReelType,
    date: 'Yesterday',
    likes: '196',
    comments: '177',
    views: '4.2K',
    viewsRaw: 4168,
    perfPct: 3,
    perfColor: 'indigo',
    isBest: false,
    url: 'https://www.instagram.com/p/DYICRDcTFVz/',
  },
  {
    id: '3891183093393060316',
    emoji: '💬',
    thumbGradient: 'linear-gradient(135deg,#134e4a,#0f766e)',
    title: '"I just hired 144 employees. Paid nothing. They all live inside Claude."',
    type: 'Story' as ReelType,
    date: '4 days ago',
    likes: '1.5K',
    comments: '6.6K',
    views: '29.6K',
    viewsRaw: 29610,
    perfPct: 24,
    perfColor: 'green',
    isBest: false,
    url: 'https://www.instagram.com/p/DYAQmg1svHc/',
  },
  {
    id: '3889787871725332242',
    emoji: '🎓',
    thumbGradient: 'linear-gradient(135deg,#4c1d95,#6d28d9)',
    title: '"Don\'t implement AI until you read this — 500+ business owners, 5 countries, same mistakes"',
    type: 'Educational' as ReelType,
    date: '6 days ago',
    likes: '214',
    comments: '395',
    views: '5.7K',
    viewsRaw: 5665,
    perfPct: 5,
    perfColor: 'indigo',
    isBest: false,
    url: 'https://www.instagram.com/p/DX7TXXZz6cS/',
  },
  {
    id: '3887593820882295776',
    emoji: '🎓',
    thumbGradient: 'linear-gradient(135deg,#78350f,#b45309)',
    title: '"Meta has officially given Claude Code access to your ads — create campaigns in one prompt"',
    type: 'Educational' as ReelType,
    date: '1 week ago',
    likes: '3.1K',
    comments: '140',
    views: '60.0K',
    viewsRaw: 59963,
    perfPct: 49,
    perfColor: 'indigo',
    isBest: false,
    url: 'https://www.instagram.com/p/DXzgfuUsVvg/',
  },
  {
    id: '3885915356870483321',
    emoji: '💬',
    thumbGradient: 'linear-gradient(135deg,#14532d,#15803d)',
    title: '"I gained 50,000 followers in 17 days using Claude AI — no ads, no collabs, just 3 skills"',
    type: 'Story' as ReelType,
    date: '1 week ago',
    likes: '3.5K',
    comments: '10.5K',
    views: '122.7K',
    viewsRaw: 122744,
    perfPct: 100,
    perfColor: 'green',
    isBest: true,
    url: 'https://www.instagram.com/p/DXti225gB15/',
  },
]
